name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t spam-classifier .

      - name: Run tests inside container
        run: docker run spam-classifier pytest test_app.py